name: Build Kivy APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    # ★ SDK를 "오직 하나"만 사용: Buildozer 내부 SDK 경로로 고정
    env:
      ANDROID_HOME:     ${{ github.workspace }}/.buildozer/android/platform/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/.buildozer/android/platform/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install build deps (Python/Buildozer)
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install "cython==0.29.36" buildozer

      # ★ Buildozer 내부 SDK 루트에 cmdline-tools 설치 (sdkmanager 제공)
      - name: Install Android cmdline-tools (into Buildozer SDK root)
        run: |
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          cd "$ANDROID_HOME/cmdline-tools"
          curl -L -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q cmdtools.zip
          rm cmdtools.zip
          mkdir -p latest
          mv cmdline-tools/* latest/

      # ★ PATH 에 Buildozer 내부 SDK 만 추가 (한 루트만 사용)
      - name: Add Android tools to PATH
        run: |
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools"           >> $GITHUB_PATH
          echo "$ANDROID_HOME/build-tools/36.0.0"       >> $GITHUB_PATH

      # ★ 같은 루트(위 ANDROID_HOME)로 라이선스 동의 + 필요한 패키지 설치
      - name: Accept licenses & install SDK packages
        env:
          SDKMAN: ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin/sdkmanager
        run: |
          # 라이선스 동의
          yes | "$SDKMAN" --sdk_root="$ANDROID_HOME" --licenses
          # 필요한 패키지(aidl 포함) 설치
          "$SDKMAN" --sdk_root="$ANDROID_HOME" \
            "platform-tools" "platforms;android-34" "build-tools;36.0.0"

      # ★ 빌드 (동일 루트 사용)
      - name: Build APK
        env:
          ANDROID_HOME:     ${{ env.ANDROID_HOME }}
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
